version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: streamlit run app/main.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: yourstreamlitapp:latest