services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run app/main.py --server.port 8501
    volumes:
      - './:/usr/src/app'
    ports:
      - '8501:8501'
    image: 'yourstreamlitapp:latest'
    env_file: 
      - .env
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
      - ./my.cnf:/etc/mysql/my.cnf
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data: